astradb:
  database-id: ${ASTRADB_DATABASE_ID}
  region: us-east-2
  keyspace: pdfassistant
  table: pdfchat

embedding:
  model-dimension: 384
  max-segment-chars: 300
  max-overlap-tokens: 0

access-token:
  openai-token: ${OPENAI_ACCESS_TOKEN}
  astradb-token: ${ASTRADB_ACCESS_TOKEN}

server:
  port: 8080
